name: PureChat
main: _64FF00\PureChat\PureChat
version: "1.3.0"
api: [1.12.0]
load: STARTUP
author: 64FF00
website: https://github.com/PurePlugins/PureChat
depend: [PurePerms]
softdepend: [FactionsPro]