
# PureChat by 64FF00 (xktiverz@gmail.com, @64ff00 for Twitter)

---

# Set default factions plugin for PureChat
# - FactionsPro / XeviousPE-Factions / null
default-factions-plugin: ~

# Enable this if you want to use per-world chat formats / per-world nametags for players
# - true / false
enable-multiworld-chat: false

# Please check if you have all PurePerms groups in your server here

# &0: Black, &1: Dark Blue, &2: Dark Green, &3: Dark Aqua, &4: Dark Red, &5: Dark Purple, &6: Gold, &7: Gray, &8: Dark Gray, &9: Blue
# &a: Green, &b: Aqua, &c: Red, &d: Light Purple, &e: Yellow, &f: White
# &k: Obfuscated, &l: Bold, &m: Strikethrough, &n: Underline, &o: Italic, &r: Reset

# Available PureChat tags: {DISPLAY_NAME}, {MESSAGE}, {FACTION_NAME}, {PREFIX}, {SUFFIX}, {WORLD_NAME}
groups:
  Guest:
    chat: "&3&l{PREFIX}&e[Guest]&r {DISPLAY_NAME} &7> {MESSAGE}"
    nametag: "&3&l{PREFIX}&e[Guest]&r {DISPLAY_NAME}"
    worlds: []
  Admin:
    chat: "&3&l{PREFIX}&c[Admin]&r {DISPLAY_NAME} &7> {MESSAGE}"
    nametag: "&3&l{PREFIX}&e[Admin]&r {DISPLAY_NAME}"
    worlds: []
  Owner:
    chat: "&3&l{PREFIX}&a[Owner]&r {DISPLAY_NAME} &7> {MESSAGE}"
    nametag: "&3&l{PREFIX}&e[Owner]&r {DISPLAY_NAME}"
    worlds: []
  OP:
    chat: "&3&l{PREFIX}&9[OP]&r {DISPLAY_NAME} &7> {MESSAGE}"
    nametag: "&3&l{PREFIX}&e[OP]&r {DISPLAY_NAME}"
    worlds: []
...