---
# Allows you to use per-world chat formats
# - true / false
enable-multiworld-formats: false

# A list of all PurePerms groups
# If you have FactionsPro installed, add %faction% anywhere
groups:
  Guest:
    default: "[Guest] %user_name% > %message%"
    worlds: [] 
  Admin:
    default: "[Admin] %user_name% > %message%"
    worlds: []
  Owner: 
    default: "[Owner] %user_name% > %message%"
    worlds: []
...