---
# Allows you to use per-world chat formats
# - true / false
enable-multiworld-formats: false

# A list of all PurePerms groups
groups:
  Guest:
    # Remember that you can also use %faction% tag if you have FactionsPro plugin installed!
    default: "[Guest] %user_name% > %message%"
    worlds: [] 
  Admin:
    default: "[Admin] %user_name% > %message%"
    worlds: []
  Owner: 
    default: "[Owner] %user_name% > %message%"
    worlds: []
...