---
# Allows you to use per-world chat formats
# - true / false
enable-multiworld-formats: false

# A list of all PurePerms groups
groups:
  Guest:
    # Default tags: {world_name}, {display_name}, {user_name}, {message}
    # Also remember that you can also use {faction} tag if you have FactionsPro plugin installed!
    default: "[Guest] {display_name} > {message}"
    worlds: [] 
  Admin:
    default: "[Admin] {display_name} > {message}"
    worlds: []
  Owner: 
    default: "[Owner] {display_name} > {message}"
    worlds: []
...